import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Admin | Settings",
    description: "Generated by create next app",
  };

const Settings = () => {
    return ( 
        <div>
            <h1>Settings</h1>
        </div>
     );
}
 
export default Settings;