import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import {Sidebar} from '@/components/layout/Sidebar';
import {Navbar} from '@/components/layout/Navbar';
import "@/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Admin",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div>
            <Navbar/>
            <div className="page-wrapper">
                <Sidebar/>
                <div className="content-wrapper">
                  {children}
                </div>
            </div>
        </div>
      </body>
    </html>
  );
}
