import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "About Us",
    description: "Generated by create next app",
  };

const About = () => {
    return ( 
        <div>
            <h1>About Us</h1>
            <p>Lorem Ipsum</p>
        </div>
     );
}
 
export default About;